device = "cuda"
# device = "cpu"
# MAX_SEQ = 128
EMBED_DIMS = 32
ENC_HEADS = DEC_HEADS = 4
NUM_ENCODER = NUM_DECODER = 6
BATCH_SIZE = 128
TRAIN_FILE = "data/train_sub.csv"
QUESTIONS_FILE = "data/questions.csv"
TOTAL_EXE = 13523
TOTAL_CAT = 13523
DROPOUT = 0.2
EPOCHS = 20
NUM_WORKS = 16
ASSIST_EXE = 3162
